In [34]:
import pandas as pd
import statsmodels.api as sm

y = natural gas consumption

x1 = average hourly temperature

x2 = the chill index

In [35]:
df = pd.DataFrame({
    "y": [12.4, 11.7, 12.4, 10.8, 9.4, 9.5, 8.0, 7.5],
    "x1": [28.0, 28.0, 32.5, 39.0, 45.9, 57.8, 58.1, 62.5],
    "x2": [18, 14, 24, 22, 8, 16, 1, 0]
})
df

      y    x1  x2
0  12.4  28.0  18
1  11.7  28.0  14
2  12.4  32.5  24
3  10.8  39.0  22
4   9.4  45.9   8
5   9.5  57.8  16
6   8.0  58.1   1
7   7.5  62.5   0

In [39]:
X = df[["x1", "x2"]]
X = sm.add_constant(X)
y = df["y"]

model = sm.OLS(y, X).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.974
Model:                            OLS   Adj. R-squared:                  0.963
Method:                 Least Squares   F-statistic:                     92.30
Date:                Tue, 06 Jan 2026   Prob (F-statistic):           0.000113
Time:                        08:51:37   Log-Likelihood:                -1.4541
No. Observations:                   8   AIC:                             8.908
Df Residuals:                       5   BIC:                             9.146
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         13.1087      0.856     15.319      0.000      10.909      15.308
x1            -0.0900      0.014     -6.394      0.001      -0.126      -0.054
x2             0.0825      0.022      3.749      0.013       0.026       0.139
==============================================================================
Omnibus:                        3.054   Durbin-Watson:                   2.073
Prob(Omnibus):                  0.217   Jarque-Bera (JB):                1.072
Skew:                          -0.895   Prob(JB):                        0.585
Kurtosis:                       2.902   Cond. No.                         311.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

b1 = -0.0900

b2 = 0.0825

In [37]:
model.model.exog_names

['const', 'x1', 'x2']

In [38]:
htemperature = 40
chill_index = 10

prediction = model.get_prediction([1, htemperature, chill_index])
prediction.summary_frame(alpha=0.05)

,mean,mean_se,mean_ci_lower,mean_ci_upper,obs_ci_lower,obs_ci_upper
0,10.333132,0.170472,9.894921,10.771343,9.292739,11.373526