In [2]:
import pandas as pd
import statsmodels.api as sm

y = sales price of a house (in thousands of dollars)

x1 = home size (in hundreds of square feet)

x2 = rating (an overall “niceness rating” for the house expressed on a scale from 1 [worst] to 10 [best], and provided by the real estate
agency)

In [3]:
df = pd.DataFrame({
    "y":  [180, 98.1, 173.1, 136.5, 141, 165.9, 193.5, 127.8, 163.5, 172.5],
    "x1": [23, 11, 20, 17, 15, 21, 24, 13, 19, 25],
    "x2": [5,  2,  9,  3,  8,  4,  7,  6,  7,  2]
})
df

       y  x1  x2
0  180.0  23   5
1   98.1  11   2
2  173.1  20   9
3  136.5  17   3
4  141.0  15   8
5  165.9  21   4
6  193.5  24   7
7  127.8  13   6
8  163.5  19   7
9  172.5  25   2

In [4]:
X = df[["x1", "x2"]]
y = df["y"]

X = sm.add_constant(X)
model = sm.OLS(y, X).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.990
Model:                            OLS   Adj. R-squared:                  0.987
Method:                 Least Squares   F-statistic:                     350.9
Date:                Tue, 06 Jan 2026   Prob (F-statistic):           9.58e-08
Time:                        08:51:27   Log-Likelihood:                -24.167
No. Observations:                  10   AIC:                             54.33
Df Residuals:                       7   BIC:                             55.24
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         29.3468      4.891      6.000      0.001      17.780      40.913
x1             5.6128      0.229     24.561      0.000       5.072       6.153
x2             3.8344      0.433      8.851      0.000       2.810       4.859
==============================================================================
Omnibus:                        1.482   Durbin-Watson:                   1.555
Prob(Omnibus):                  0.477   Jarque-Bera (JB):                0.928
Skew:                          -0.449   Prob(JB):                        0.629
Kurtosis:                       1.808   Cond. No.                         95.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

b1 = 5.6128

b2 = 3.8344

In [9]:
square_feet = 20
rating = 8

prediction = model.get_prediction([1, square_feet, rating])
prediction.summary_frame(alpha=0.05)

,mean,mean_se,mean_ci_lower,mean_ci_upper,obs_ci_lower,obs_ci_upper
0,172.278307,1.570457,168.564766,175.991849,163.760887,180.795728