In [6]:
import pandas as pd
import statsmodels.api as sm

y = the demand for the large size bottle of Fresh (in hundreds of thousands of bottles) in the sales period

x1 = the price (in dollars) of Fresh as offered by Enterprise Industries in the sales period

x2 = the average industry price (in dollars) of competitors’ similar detergents in the sales period

x3 = Enterprise Industries’ advertising expenditure (in hundreds of thousands of dollars) to promote Fresh in the sales period

In [7]:
df = pd.DataFrame({
    "period": list(range(1, 31)),
    "x1_price_fresh": [
        3.85, 3.75, 3.70, 3.70, 3.60, 3.60,
        3.60, 3.80, 3.80, 3.85, 3.90, 3.90,
        3.70, 3.75, 3.75, 3.80, 3.70, 3.80,
        3.70, 3.80, 3.80, 3.75, 3.70, 3.55,
        3.60, 3.65, 3.70, 3.75, 3.80, 3.70
    ],
    "x2_avg_industry_price": [
        3.80, 4.00, 4.30, 3.70, 3.85, 3.80,
        3.75, 3.85, 3.65, 4.00, 4.10, 4.00,
        4.10, 4.20, 4.10, 4.10, 4.20, 4.30,
        4.10, 3.75, 3.75, 3.65, 3.90, 3.65,
        4.10, 4.25, 3.65, 3.75, 3.85, 4.25
    ],
    "x3_advertising": [
        5.50, 6.75, 7.25, 5.50, 7.00, 6.50,
        6.75, 5.25, 5.25, 6.00, 6.50, 6.25,
        7.00, 6.90, 6.80, 6.80, 7.10, 7.00,
        6.80, 6.50, 6.25, 6.00, 6.50, 7.00,
        6.80, 6.80, 6.50, 5.75, 5.80, 6.80
    ],
    "y_demand": [
        7.38, 8.51, 9.52, 7.50, 9.33, 8.28,
        8.75, 7.87, 7.10, 8.00, 7.89, 8.15,
        9.10, 8.86, 8.90, 8.87, 9.26, 9.00,
        8.75, 7.95, 7.65, 7.27, 8.00, 8.50,
        8.75, 9.21, 8.27, 7.67, 7.93, 9.26
    ]
})

df

    period  x1_price_fresh  x2_avg_industry_price  x3_advertising  y_demand
0        1            3.85                   3.80            5.50      7.38
1        2            3.75                   4.00            6.75      8.51
2        3            3.70                   4.30            7.25      9.52
3        4            3.70                   3.70            5.50      7.50
4        5            3.60                   3.85            7.00      9.33
5        6            3.60                   3.80            6.50      8.28
6        7            3.60                   3.75            6.75      8.75
7        8            3.80                   3.85            5.25      7.87
8        9            3.80                   3.65            5.25      7.10
9       10            3.85                   4.00            6.00      8.00
10      11            3.90                   4.10            6.50      7.89
11      12            3.90                   4.00            6.25      8.15
12      13            3.70                   4.10            7.00      9.10
13      14            3.75                   4.20            6.90      8.86
14      15            3.75                   4.10            6.80      8.90
15      16            3.80                   4.10            6.80      8.87
16      17            3.70                   4.20            7.10      9.26
17      18            3.80                   4.30            7.00      9.00
18      19            3.70                   4.10            6.80      8.75
19      20            3.80                   3.75            6.50      7.95
20      21            3.80                   3.75            6.25      7.65
21      22            3.75                   3.65            6.00      7.27
22      23            3.70                   3.90            6.50      8.00
23      24            3.55                   3.65            7.00      8.50
24      25            3.60                   4.10            6.80      8.75
25      26            3.65                   4.25            6.80      9.21
26      27            3.70                   3.65            6.50      8.27
27      28            3.75                   3.75            5.75      7.67
28      29            3.80                   3.85            5.80      7.93
29      30            3.70                   4.25            6.80      9.26

In [8]:
X = df[['x1_price_fresh', 'x2_avg_industry_price', 'x3_advertising']]
y = df['y_demand']

X = sm.add_constant(X)
model = sm.OLS(y, X).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:               y_demand   R-squared:                       0.894
Model:                            OLS   Adj. R-squared:                  0.881
Method:                 Least Squares   F-statistic:                     72.80
Date:                Tue, 06 Jan 2026   Prob (F-statistic):           8.88e-13
Time:                        09:07:57   Log-Likelihood:                 3.0657
No. Observations:                  30   AIC:                             1.869
Df Residuals:                      26   BIC:                             7.473
Df Model:                           3
Covariance Type:            nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
const                     7.5891      2.445      3.104      0.005       2.563      12.615
x1_price_fresh           -2.3577      0.638     -3.696      0.001      -3.669      -1.046
x2_avg_industry_price     1.6122      0.295      5.459      0.000       1.005       2.219
x3_advertising            0.5012      0.126      3.981      0.000       0.242       0.760
==============================================================================
Omnibus:                        0.134   Durbin-Watson:                   1.788
Prob(Omnibus):                  0.935   Jarque-Bera (JB):                0.039
Skew:                           0.061   Prob(JB):                        0.980
Kurtosis:                       2.870   Cond. No.                         501.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

β1 = -2.3577

β2 = 1.6122

β3 = 0.5012

In [10]:
x1=3.70
x2=3.90
x3=6.50

prediction = model.get_prediction([1, x1, x2, x3])
prediction.summary_frame(alpha=0.5)

      mean   mean_se  mean_ci_lower  mean_ci_upper  obs_ci_lower  obs_ci_upper
0  8.41065  0.046865       8.378592       8.442708      8.246957      8.574344